language: go
branches:
  only:
    - master
matrix:
  include:
    - go: 1.11.x
    - go: 1.16.x
env:
  - GO111MODULE=on
before_cache:
- rm -rf $GOPATH/pkg/**/github.com/googleworkspace/go-samples
cache:
  directories:
    - $GOPATH/pkg
install:
# Install all external dependencies, ensuring they are updated.
- go mod download
- export CI=TRAVIS # for gotest to force colors
script:
- go vet ./...
- go fmt ./...
# - travis_wait 20 gotest -p 10 -timeout 20m -v ./...;
